#!/bin/sh

case $PINENTRY_USER_DATA in
    curses)
        exec pinentry-curses "$@"
        ;;
    tty)
        exec pinentry-tty "$@"
        ;;
    null)
        # do nothing
        ;;
    *)
        if type pinentry-mac &>/dev/null; then
            exec pinentry-mac "$@"
        else
            exec pinentry-qt "$@"
        fi
        ;;
esac
