#!/bin/sh

case $PINENTRY_USER_DATA in
curses)
    exec pinentry-curses "$@"
    ;;
null)
    # do nothing
    ;;
tmux*)
    pane=${PINENTRY_USER_DATA#tmux}
    pane=${pane#:}
    dir=$(mktemp -d)
    mkfifo "$dir/in" "$dir/out" "$dir/tty"
    tmux display-popup -b rounded -S 'fg=#ec5f67' -E ${pane:+-t "$pane"} -w 60 -h 7 \
        "tty >'$dir/tty'; exec pinentry-tty <'$dir/in' >'$dir/out'" &
    popup_tty=$(cat "$dir/tty")
    exec 3>&1
    cat "$dir/out" &
    while IFS= read -r line; do
        case $line in
        "OPTION ttyname="*)
            line="OPTION ttyname=$popup_tty"
            ;;
        "OPTION allow-external-password-cache"*)
            printf 'OK\n' >&3
            continue
            ;;
        esac
        printf '%s\n' "$line"
    done >"$dir/in"
    exec 3>&-
    wait
    rm -rf "$dir"
    ;;
tty)
    exec pinentry-tty "$@"
    ;;
*)
    if type pinentry-mac >/dev/null 2>&1; then
        exec pinentry-mac "$@"
    else
        exec pinentry-qt "$@"
    fi
    ;;
esac
