#!/bin/sh

case $PINENTRY_USER_DATA in
    USE_CURSES=1)
        exec pinentry-curses "$@"
        ;;
    NO_PINENTRY=1)
        # do nothing
        ;;
    *)
        if type pinentry-mac &>/dev/null; then
            exec pinentry-mac "$@"
        else
            exec pinentry-qt "$@"
        fi
        ;;
esac
