#!/bin/bash

export NOTMUCH_PROFILE="${1}"

nm_path="$(notmuch config get database.path)"

echo "virtual-mailboxes '$1' 'notmuch://${nm_path}?query=tag:\\Inbox -folder:Trash'"
echo "virtual-mailboxes '  Unread' 'notmuch://${nm_path}?query=tag:unread -folder:Trash'"
echo "virtual-mailboxes '  Flagged' 'notmuch://${nm_path}?query=tag:flagged -folder:Trash'"
echo "virtual-mailboxes '  Important' 'notmuch://${nm_path}?query=tag:\\Important -folder:Trash'"
echo "virtual-mailboxes '  Sent' 'notmuch://${nm_path}?query=tag:\\Sent -folder:Trash'"
echo "virtual-mailboxes '  Draft' 'notmuch://${nm_path}?query=tag:\\Draft -folder:Trash'"
echo "virtual-mailboxes '  Trash' 'notmuch://${nm_path}?query=tag:\\Trash or folder:Trash'"

~/.config/neomutt/notmuch2mailbox "$1" "$2" '  '
