#!/bin/bash

if [[ -n "$1" ]]; then
    export NOTMUCH_CONFIG="${HOME}/.config/notmuch/${1}"
fi

nm_path="$(notmuch config get database.path)"

notmuch search --output=tags '*' |
while read -r line; do
    if [[ -z "${line}" ]]; then
        continue
    fi
    if [[ ${line} =~ ^\\ ]]; then
        # ignore gmail system labels
        continue
    fi
    if [[ ${line} =~ ^attachment|draft|encrypted|flagged|passed|replied|signed|unread$ ]]; then
        # ignore maildir flags
        continue
    fi
    echo "virtual-mailboxes '$2$line' 'notmuch://${nm_path}?query=tag:$line'"
done
