#!/bin/bash

if [[ -n "$1" ]]; then
    export NOTMUCH_PROFILE="${1}"
fi

ALL_TAGS=${2:-1}

nm_path="$(notmuch config get database.path)"

notmuch search --output=tags '*' |
while read -r line; do
    if [[ -z "${line}" ]]; then
        continue
    fi
    if [[ ${line} =~ ^\\ ]]; then
        # ignore gmail system labels
        continue
    fi
    if [[ ${line} =~ ^attachment|draft|encrypted|flagged|passed|replied|signed|unread$ ]]; then
        # ignore maildir flags
        continue
    fi
    if [[ $ALL_TAGS != 1 && ${line} =~ ^[a-z] ]]; then
        continue
    fi
    echo "virtual-mailboxes '$3$line' 'notmuch://${nm_path}?query=tag:$line -folder:Trash'"
done
