#!/bin/sh

# Common rc for interactive shells (zsh, bash, ksh, ...).

# Switch to zsh if available.
if [ -z "$ZSH_VERSION" ]; then
    case "$-" in *i*)
        if command -v zsh >/dev/null 2>&1; then
            SHELL=$(command -v zsh)
            export SHELL
            exec "$SHELL" -l
        fi
        ;;
    esac
fi

for profile in ~/.config/sh/shrc.d/*.sh; do
    . "$profile"
done
unset profile
